{
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python24"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "2.4.5_2"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python25"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "2.5.2_3"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python23"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0,1"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2008-08-04T00:00:00Z",
        "vid": "0dccaa28-7f3c-11dd-8de5-0030843d3802"
    },
    "details": "Secunia reports:\n\n> Some vulnerabilities have been reported in Python, where some have\n> unknown impact and others can potentially be exploited by malicious\n> people to cause a DoS (Denial of Service) or to compromise a\n> vulnerable system.\n>\n> Various integer overflow errors exist in core modules e.g.\n> stringobject, unicodeobject, bufferobject, longobject, tupleobject,\n> stropmodule, gcmodule, mmapmodule.\n>\n> An integer overflow in the hashlib module can lead to an unreliable\n> cryptographic digest results.\n>\n> Integer overflow errors in the processing of unicode strings can be\n> exploited to cause buffer overflows on 32-bit systems.\n>\n> An integer overflow exists in the PyOS\\_vsnprintf() function on\n> architectures that do not have a \"vsnprintf()\" function.\n>\n> An integer underflow error in the PyOS\\_vsnprintf() function when\n> passing zero-length strings can lead to memory corruption.",
    "id": "FreeBSD-kernel-2008-0072",
    "modified": "2008-09-10T00:00:00Z",
    "published": "2008-09-10T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2008-2315"
        },
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2008-2316"
        },
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2008-3142"
        },
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2008-3144"
        },
        {
            "type": "WEB",
            "url": "http://bugs.python.org/issue2620"
        },
        {
            "type": "WEB",
            "url": "http://bugs.python.org/issue2588"
        },
        {
            "type": "WEB",
            "url": "http://bugs.python.org/issue2589"
        },
        {
            "type": "WEB",
            "url": "http://secunia.com/advisories/31305"
        },
        {
            "type": "DISCUSSION",
            "url": "http://mail.python.org/pipermail/python-checkins/2008-July/072276.html"
        },
        {
            "type": "DISCUSSION",
            "url": "http://mail.python.org/pipermail/python-checkins/2008-July/072174.html"
        },
        {
            "type": "DISCUSSION",
            "url": "http://mail.python.org/pipermail/python-checkins/2008-June/070481.html"
        }
    ],
    "schema_version": "1.7.0",
    "summary": "python -- multiple vulnerabilities"
}
