{
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py36-matrix-synapse"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "1.19.2"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py37-matrix-synapse"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "1.19.2"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        },
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "py38-matrix-synapse"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "1.19.2"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2020-09-16T00:00:00Z",
        "vid": "2327234d-fc4b-11ea-adef-641c67a117d8"
    },
    "details": "Problem Description:\n====================\n\nAffected Synapse versions assume that all events have an \"origin\" field set. If an event\nwithout the \"origin\" field is sent into a federated room, servers not already joined to\nthe room will be unable to do so due to failing to fetch the malformed event.\n\nImpact:\n=======\n\nAn attacker could cause a denial of service by deliberately sending a malformed event\ninto a room, thus preventing new servers (and thus their users) from joining the\nroom.",
    "id": "FreeBSD-kernel-2020-0082",
    "modified": "2020-09-21T00:00:00Z",
    "published": "2020-09-21T00:00:00Z",
    "references": [
        {
            "type": "WEB",
            "url": "https://github.com/matrix-org/synapse/issues/8319"
        },
        {
            "type": "WEB",
            "url": "https://github.com/matrix-org/synapse/pull/8324"
        },
        {
            "type": "WEB",
            "url": "https://github.com/matrix-org/synapse/blob/v1.19.3/CHANGES.md"
        }
    ],
    "schema_version": "1.7.0",
    "summary": "py-matrix-synapse -- malformed events may prevent users from joining federated rooms"
}
