{
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "python38"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "3.8.5"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2020-02-11T00:00:00Z",
        "vid": "7d7221ee-d334-11ea-bc50-080027846a02"
    },
    "details": "Python reports:\n\n> bpo-41304: Fixes python3x.\\_pth being ignored on Windows, caused by the fix for\n> bpo-29778 (CVE-2020-15801).\n>\n> bpo-39603: Prevent http header injection by rejecting control characters in\n> http.client.putreques().",
    "id": "FreeBSD-kernel-2020-0141",
    "modified": "2020-07-31T00:00:00Z",
    "published": "2020-07-31T00:00:00Z",
    "references": [
        {
            "type": "WEB",
            "url": "https://docs.python.org/3/whatsnew/changelog.html#python-3-8-5-final"
        },
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2020-15801"
        }
    ],
    "schema_version": "1.7.0",
    "summary": "Python -- multiple vulnerabilities"
}
