{
    "affected": [
        {
            "package": {
                "ecosystem": "FreeBSD:ports",
                "name": "pglogical"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "fixed": "2.3.4"
                        },
                        {
                            "introduced": "0"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "database_specific": {
        "discovery": "2021-06-01T00:00:00Z",
        "vid": "45b8716b-c707-11eb-b9a0-6805ca0b3d42"
    },
    "details": "2ndQuadrant reports:\n\n> * Fix pg\\_dump/pg\\_restore execution (CVE-2021-3515)  \n>     \n>   Correctly escape the connection string for both pg\\_dump\n>   and pg\\_restore so that exotic database and user names are\n>   handled correctly.  \n>     \n>   Reported by Pedro Gallegos",
    "id": "FreeBSD-kernel-2021-0161",
    "modified": "2021-06-06T00:00:00Z",
    "published": "2021-06-06T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://api.osv.dev/v1/vulns/CVE-2021-3515"
        },
        {
            "type": "WEB",
            "url": "https://github.com/2ndQuadrant/pglogical/releases/tag/REL2_3_4"
        },
        {
            "type": "REPORT",
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1954112"
        }
    ],
    "schema_version": "1.7.0",
    "summary": "pglogical -- shell command injection in pglogical.create_subscription()"
}
